version: "3.9"

services:
  # ----------------- Databases -----------------
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: laravel_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - trainer_net

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - trainer_net

  redis:
    image: redis:7
    container_name: user_service_redis
    ports:
      - "6379:6379"

  # ----------------- RabbitMQ -----------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ broker
      - "15672:15672"  # Management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - trainer_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
  # ----------------- Laravel Gateway -----------------
  gateway-service:
    build: ./services/gateway
    container_name: gateway_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
      APP_ENV: local
      APP_DEBUG: "true"
    ports:
      - "8080:8000"
    networks:
      - trainer_net

  # ----------------- Laravel User Service -----------------
  user-service:
    build: ./services/laravel/users
    container_name: user_service
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_DATABASE: laravel_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
      JWT_SECRET: test
    ports:
      - "8001:8000"
    networks:
      - trainer_net

  # ----------------- NestJS Chatbot Service -----------------
  # chatbot:
  #   container_name: chatbot
  #   build:
  #     context: ./service/nestJS
  #     args:
  #       APP_NAME: chatbot
  #   environment:
  #     - APP_NAME=chatbot
  #     - MONGO_URI=mongodb://mongo:27017/chatbot_db
  #     - NODE_ENV=development
  #   depends_on:
  #     mongo:
  #       condition: service_started
  #     rabbitmq:
  #       condition: service_healthy
  #   ports:
  #     - "3001:3000"
  #   command: ["sh", "-c", "npm run start:dev chatbot-service"]
  #   restart: unless-stopped
  #   networks:
  #     - trainer_net

  # # ----------------- NestJS stream Service -----------------
  # stream-service:
  #   container_name: stream-service
  #   build:
  #     context: ./service/nestJS
  #     args:
  #       APP_NAME: stream-service
  #   environment:
  #     - APP_NAME=stream-service
  #     - MONGO_URI=mongodb://mongo:27017/stream_db
  #     - NODE_ENV=development
  #   volumes:
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     mongo:
  #       condition: service_started
  #     rabbitmq:
  #       condition: service_healthy
  #   ports:
  #     - "3001:3000"
  #   command: ["sh", "-c", "npm run start:dev stream-service"]
  #   restart: unless-stopped
  #   networks:
  #     - trainer_net

  #   # ----------------- NestJS notification Service -----------------
  # notification-service:
  #   container_name: notification-service
  #   build:
  #     context: ./service/nestJS
  #     args:
  #       APP_NAME: notification-service
  #   environment:
  #     APP_NAME: notification-service
  #     DB_CONNECTION: pgsql
  #     DB_HOST: postgres_db
  #     DB_PORT: 5432
  #     DB_DATABASE: notification_db
  #     DB_USERNAME: admin
  #     DB_PASSWORD: admin123
  #     NODE_ENV: development
  #   volumes:
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     postgres:
  #       condition: service_started
  #     rabbitmq:
  #       condition: service_healthy
  #   ports:
  #     - "3002:3000"
  #   command: ["sh", "-c", "npm run start:dev stream-service"]
  #   restart: unless-stopped
  #   networks:
  #     - trainer_net

networks:
  trainer_net:
    driver: bridge

volumes:
  pgdata:
  mongodata:
  rabbitmq_data: