version: "3.9"

services:
  # ----------------- Databases -----------------
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: laravel_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  # ----------------- Laravel Service -----------------
  laravel-service:
    build: ./services/laravel/ai-trainer
    container_name: laravel_service
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_DATABASE: laravel_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    ports:
      - "8000:8000"

  # ----------------- Optional Services -----------------
  # dotnet-service:
  #   build: ./services/dotnet
  #   container_name: dotnet_service
  #   depends_on:
  #     - postgres
  #   environment:
  #     ASPNETCORE_URLS: http://+:5000
  #     ConnectionStrings__Default: Host=postgres;Database=trainer_main;Username=admin;Password=admin123
  #   ports:
  #     - "5000:5000"

  # nest-service:
  #   build: ./services/nestJS
  #   container_name: nest_service
  #   depends_on:
  #     - mongo
  #   environment:
  #     MONGO_URI: mongodb://mongo:27017/nestdb
  #   ports:
  #     - "3000:3000"

  # ai-models:
  #   build: ./ai-models
  #   container_name: ai_models
  #   ports:
  #     - "8001:8001"

 # ----------------- API Gateway -----------------
  api-gateway:
    image: nginx:1.25
    container_name: api_gateway
    depends_on:
      # - dotnet-service
      - laravel-service
      # - nest-service
      # - ai-models
    ports:
      - "8080:80"
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
  mongodata:
