services:
  # ----------------- RabbitMQ -----------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ broker
      - "15672:15672" # Management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - trainer_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------Gateway-----------------
  gateway:
    container_name: gateway
    build:
      context: ./services/gateway
    env_file:
      - ./services/gateway/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./services/gateway:/app
      - /app/node_modules
    networks:
      - trainer_net

  # ----------------- NestJS Auth Service -----------------
  auth-service:
    container_name: auth-service
    build:
      context: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3001:3000"
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start:dev
      "
    restart: unless-stopped
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    networks:
      - trainer_net

  # ----------------- NestJS Interaction Service -----------------
  interaction-service:
    container_name: interaction-service
    build:
      context: ./services/interaction-service
    env_file:
      - ./services/interaction-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3002:3000"
    command: >
      sh -c "
      npm run start:dev
      "
    restart: unless-stopped
    volumes:
      - ./services/interaction-service:/app
      - /app/node_modules
    networks:
      - trainer_net
  # ----------------- NestJS Coaching Domain Service -----------------
  coaching-service:
    container_name: coaching-service
    build:
      context: ./services/coaching-service
    env_file:
      - ./services/coaching-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3003:3000"
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start:dev
      "
    restart: unless-stopped
    volumes:
      - ./services/coaching-service:/app
      - /app/node_modules
    networks:
      - trainer_net

networks:
  trainer_net:
    driver: bridge

volumes:
  rabbitmq_data:
