FROM node:22-alpine3.21

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .

# COPY public ./public

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]