export enum TraineeGoal {
    CUT = 'cut',
    BULK = 'bulk',
    MAINTENANCE = 'maintenance',
    STRENGTH = 'strength',
    BODY_RECOMB = 'body_recomb'
}

export enum Gender {
    MALE = "male",
    FEMALE = "female",
    UNKNOWN = "unknown"
}

export enum UserRole {
    TRAINER = "trainer",
    TRAINEE = "trainee",
    ADMIN = "admin"
}

export enum NotificationType {
    PASSWORD_RESET = 'PASSWORD_RESET',
    NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',
    TRAINER_RANK_CHANGED = 'TRAINER_RANK_CHANGED',
    NEW_TRAINER_REGISTERED = 'NEW_TRAINER_REGISTERED',
    NEW_TRAINEE_REQUESTED = 'NEW_TRAINEE_REQUESTED',
    TRAINEE_REQUEST_APPROVED = 'TRAINEE_REQUEST_APPROVED',
    TRAINEE_REQUEST_REJECTED = 'TRAINEE_REQUEST_REJECTED',
    MEMBERSHIP_EXPIRED = 'MEMBERSHIP_EXPIRED',
    WORKOUT_PLAN_ASSIGNED = 'WORKOUT_PLAN_ASSIGNED',
    WORKOUT_PLAN_UNASSIGNED = 'WORKOUT_PLAN_UNASSIGNED',
    NUTRITION_PLAN_ASSIGNED = 'NUTRITION_PLAN_ASSIGNED',
    NUTRITION_PLAN_UNASSIGNED = 'NUTRITION_PLAN_UNASSIGNED',
    TRAINER_UNASSIGNED = 'TRAINER_UNASSIGNED',
    BODY_WEIGHT_LOGGED = 'BODY_WEIGHT_LOGGED',
    TRAINER_PROFILE_UPDATE = 'TRAINER_PROFILE_UPDATE',
    TRAINEE_DELOAD_DETECTED = 'TRAINEE_DELOAD_DETECTED',
}