export enum ActivityType {
    WORKOUT_COMPLETED = "WORKOUT_COMPLETED",
    NUTRITION_PLAN_ASSIGNED = "NUTRITION_PLAN_ASSIGNED",
    WEIGHT_LOGGED = "WEIGHT_LOGGED",
    TRAINER_REQUESTED = "TRAINER_REQUESTED",
    MEMBERSHIP_RENEWED = "MEMBERSHIP_RENEWED",
    TRAINER_APPROVED = "TRAINER_APPROVED",
    PASSWORD_CHANGED = "PASSWORD_CHANGED",
    CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED",
    TRAINER_RANK_CHANGED = "TRAINER_RANK_CHANGED",
}