services:
  # Databases

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  # Nest apps (one service per app)
  chatbot:
    container_name: chatbot
    build:
      context: .
      args:
        APP_NAME: chatbot
    environment:
      - APP_NAME=chatbot
      - MONGO_URI=mongodb://mongo:27017/nestdb
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app:delegated # mount repo into container (fast on Linux)
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - "3001:3000"
    command: ["sh", "-c", "npm run start:dev chatbot"]
    restart: unless-stopped

  stream-service:
    container_name: stream-service
    build:
      context: .
      args:
        APP_NAME: stream-service
    environment:
      - APP_NAME=stream-service
      - MONGO_URI=mongodb://mongo:27017/nestdb
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app:delegated
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - "3002:3000"
    command: ["sh", "-c", "npm run start:dev stream-service"]
    restart: unless-stopped

  workout:
    container_name: workout
    build:
      context: .
      args:
        APP_NAME: workout
    environment:
      - APP_NAME=workout
      - MONGO_URI=mongodb://mongo:27017/nestdb
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app:delegated
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - "3003:3000"
    command: ["sh", "-c", "npm run start:dev workout"]
    restart: unless-stopped

volumes:
  mongodata:
